### ISSUE TITLE
Embed in Notebook

### ISSUE THREAD

**Issue by psychemedia** [guettel/youteach#1]
Have you looked at doing this in a single Jupyter notebook?

Eg you can create an iframe in a pop-up dialog in a notebook using something like:

```
%%javascript

var yt_div = document.createElement("div"); 
yt_div.setAttribute("id", "popmeout");

var yt_iframe = document.createElement("iframe"); 
// iframe code here

yt_div.appendChild(yt_iframe);
document.getElementsByTagName("body")[0].appendChild(yt_diframe);

// Display dialog
$("#popmeout").dialog();
```

Then use anchored tags for headings in the notebook and [`.scrollintoview()`](https://www.w3schools.com/jsref/met_element_scrollintoview.asp) to synch the notebook and the video?

The script could presumably be put into the notebook metadata if you wanted to have everything in a single document?

**Comment by guettel** [comment]
Hi, thanks for the comment! I briefly played with this option and in principle this could work as well. However, I also had some problems with this: 

* the YouTube video would sometimes need to be moved around to not overlay the lecture notes (note that it' position would need to be absolute, otherwise it would scroll out of view with the notebook) 
* if I also make the timestamp list movable together with the video, then this window becomes too big and would use similar screen space to what's available now 
* on mobile phones, the touch dragging of the YouTube iframe was very laggy and sometimes fired unwanted pause/play events (I'm not claiming that in-browser coding is very practical on small mobile screens, but didn't want to exclude phones&tablets).

So to keep things simple, I eventually decided to go for the resizable three-column layout.

**Comment by psychemedia** [comment]
I agree that on mobile a different display might be useful.

Re: the widget overlapping notebook display, I've been using a widget that floats agains scrolling notebook dodged left:

```
#Reset the notebook style
from IPython.core.display import display, HTML

# Push the notebook display to the left of the page
display(HTML("<style>#notebook-container { width:50% !important; float:left !important;}</style>"))
```

We can also make that view draggable so you can drag the side of the display to give you a wider or narrower notebook view.

![](https://github.com/innovationOUtside/nbev3devsim/raw/master/.images/ev3devsim_demo_screenshot.png)

I started exploring [an extension](https://github.com/innovationOUtside/nbev3devsim/tree/master/nb_cell_tools/) (undocumented atm) for adding toolbar buttons that let you enable the dodged left display, though IIRC it doesn't toggle back to the central view atm. (The extension also supports pushing a cell output to a two column display dodged left of the code input.)
